jobs: 2000
latency-wait: 60
restart-times: 3
jobname: "snakemake_{rule}_{wildcards}_{jobid}"
jobscript: "slurm-jobscript.sh"
cluster: "{{cookiecutter.submit_script}}"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
